name: Deploy render.test.html to GitHub Pages
permissions:
  id-token: write
  pages: write
  actions: read
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Copiar componentes UI e página de navegação
        run: |
          mkdir -r public/
          cp -r templates/ public/templates
          cp -r static/ public/static
          cp -r render.test.html public/index.html
          cp -r render.test.js public/render.test.js
          cp -r render.test.json public/render.test.json
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
